#!/usr/bin/env bash
set -euo pipefail

DEFAULT_CONFIG="${HOME}/.codex/remote-ssh-v0.toml"
DEFAULT_REMOTE_PORT=9234
LOCAL_PORT_START=47000
LOCAL_PORT_END=48999

usage() {
  cat <<'EOF'
Prepare a normal SSH host for Codex desktop's hidden remote-host flow.

Usage:
  codex-remote.sh --ssh-host HOST [options]
  codex-remote.sh --ssh-alias NAME [options]

Options:
  --ssh-host HOST        SSH target, such as user@host.
  --ssh-alias NAME       SSH alias from ~/.ssh/config.
  --ssh-port PORT        Override the SSH port.
  --identity PATH        Override the SSH identity file.
  --display-name NAME    Label to store in the Codex config.
  --local-port PORT      Local tunnel port for Codex to use.
  --remote-port PORT     Remote `codex app-server` port. Defaults to 9234.
  --config PATH          Output path. Defaults to ~/.codex/remote-ssh-v0.toml.
  --apply                Write the config. Without this, only run checks.
  --help                 Show this help text.

Examples:
  ./codex-remote.sh --ssh-host <user>@<host>
  ./codex-remote.sh --ssh-host <user>@<host> --apply
  ./codex-remote.sh --ssh-alias <alias> --apply
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

pass() {
  printf 'PASS  %s\n' "$*"
}

info() {
  printf '%s\n' "$*"
}

warn() {
  printf 'WARN  %s\n' "$*" >&2
}

is_integer() {
  [[ "${1:-}" =~ ^[0-9]+$ ]]
}

expand_local_path() {
  case "$1" in
    "~")
      printf '%s\n' "$HOME"
      ;;
    "~/"*)
      printf '%s/%s\n' "$HOME" "${1#"~/"}"
      ;;
    *)
      printf '%s\n' "$1"
      ;;
  esac
}

lookup_ssh_value() {
  local key="$1"
  local file="$2"
  awk -v wanted="$key" '$1 == wanted { $1 = ""; sub(/^ /, ""); print; exit }' "$file"
}

pick_ssh_identity() {
  local file="$1"
  local raw_path=""
  local expanded_path=""

  while IFS= read -r raw_path; do
    [[ -n "$raw_path" && "$raw_path" != "none" ]] || continue
    expanded_path="$(expand_local_path "$raw_path")"
    if [[ -f "$expanded_path" ]]; then
      printf '%s\n' "$expanded_path"
      return 0
    fi
  done < <(awk '$1 == "identityfile" { $1 = ""; sub(/^ /, ""); print }' "$file")

  return 1
}

slugify() {
  local value
  value="$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
  [[ -n "$value" ]] || value="remote-host"
  printf '%s\n' "$value"
}

toml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

find_free_port() {
  local port
  for port in $(seq "$LOCAL_PORT_START" "$LOCAL_PORT_END"); do
    if ! lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; then
      printf '%s\n' "$port"
      return 0
    fi
  done

  return 1
}

write_config() {
  local output="$1"
  local tmp_file=""
  local backup_path=""

  mkdir -p "$(dirname "$output")"
  tmp_file="$(mktemp)"

  {
    printf '# Generated by %s on %s\n' "$(basename "$0")" "$(date '+%Y-%m-%d %H:%M:%S %Z')"
    printf 'host_id = "%s"\n' "$(toml_escape "$host_id")"
    printf 'display_name = "%s"\n' "$(toml_escape "$display_name")"
    printf 'local_port = %s\n' "$local_port"
    printf 'ssh_host = "%s"\n' "$(toml_escape "$ssh_host")"
    if [[ -n "$ssh_port" ]]; then
      printf 'ssh_port = %s\n' "$ssh_port"
    fi
    if [[ -n "$identity" ]]; then
      printf 'identity = "%s"\n' "$(toml_escape "$identity")"
    fi
    printf 'remote_port = %s\n' "$remote_port"
  } >"$tmp_file"

  if [[ -f "$output" ]]; then
    if cmp -s "$tmp_file" "$output"; then
      rm -f "$tmp_file"
      pass "Config already matches $output"
      return 0
    fi

    backup_path="${output}.bak-$(date '+%Y%m%d%H%M%S')"
    cp "$output" "$backup_path"
    pass "Backed up the previous config to $backup_path"
  fi

  mv "$tmp_file" "$output"
  chmod 600 "$output" 2>/dev/null || true
  pass "Wrote $output"
}

ssh_host=""
ssh_alias=""
ssh_port=""
identity=""
display_name=""
local_port=""
remote_port="$DEFAULT_REMOTE_PORT"
config_path="$DEFAULT_CONFIG"
apply_mode=0
resolved_file=""
host_id=""

cleanup() {
  if [[ -n "$resolved_file" && -f "$resolved_file" ]]; then
    rm -f "$resolved_file"
  fi
}
trap cleanup EXIT

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ssh-host)
      [[ $# -ge 2 ]] || die "--ssh-host requires a value"
      ssh_host="$2"
      shift 2
      ;;
    --ssh-alias)
      [[ $# -ge 2 ]] || die "--ssh-alias requires a value"
      ssh_alias="$2"
      shift 2
      ;;
    --ssh-port)
      [[ $# -ge 2 ]] || die "--ssh-port requires a value"
      ssh_port="$2"
      shift 2
      ;;
    --identity)
      [[ $# -ge 2 ]] || die "--identity requires a value"
      identity="$2"
      shift 2
      ;;
    --display-name)
      [[ $# -ge 2 ]] || die "--display-name requires a value"
      display_name="$2"
      shift 2
      ;;
    --local-port)
      [[ $# -ge 2 ]] || die "--local-port requires a value"
      local_port="$2"
      shift 2
      ;;
    --remote-port)
      [[ $# -ge 2 ]] || die "--remote-port requires a value"
      remote_port="$2"
      shift 2
      ;;
    --config)
      [[ $# -ge 2 ]] || die "--config requires a value"
      config_path="$2"
      shift 2
      ;;
    --apply)
      apply_mode=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
done

if [[ -n "$ssh_alias" ]]; then
  resolved_file="$(mktemp)"
  if ! ssh -G "$ssh_alias" >"$resolved_file"; then
    die "could not resolve SSH alias '$ssh_alias'"
  fi

  [[ -n "$ssh_host" ]] || ssh_host="$ssh_alias"
  [[ -n "$ssh_port" ]] || ssh_port="$(lookup_ssh_value port "$resolved_file" || true)"

  if [[ -z "$identity" ]]; then
    identity="$(pick_ssh_identity "$resolved_file" || true)"
  fi

  [[ -n "$display_name" ]] || display_name="$ssh_alias"
fi

[[ -n "$ssh_host" ]] || die "set --ssh-host or --ssh-alias"

if [[ -n "$identity" ]]; then
  identity="$(expand_local_path "$identity")"
  if [[ ! -f "$identity" ]]; then
    warn "Ignoring SSH identity that does not exist locally: $identity"
    identity=""
  fi
fi

if [[ -n "$ssh_port" ]] && ! is_integer "$ssh_port"; then
  die "--ssh-port must be an integer"
fi

if [[ -n "$local_port" ]] && ! is_integer "$local_port"; then
  die "--local-port must be an integer"
fi

if ! is_integer "$remote_port"; then
  die "--remote-port must be an integer"
fi

[[ -n "$display_name" ]] || display_name="$ssh_host"
[[ -n "$local_port" ]] || local_port="$(find_free_port)" || die "could not find a free local port"
host_id="$(slugify "$display_name")"

ssh_args=(-o BatchMode=yes -o ConnectTimeout=10 -o ServerAliveInterval=15 -o ServerAliveCountMax=4)
if [[ -n "$ssh_port" ]]; then
  ssh_args+=(-p "$ssh_port")
fi
if [[ -n "$identity" ]]; then
  ssh_args+=(-i "$identity")
fi

ssh_cmd=(ssh "${ssh_args[@]}" "$ssh_host")

info "Target: $ssh_host"
info "Mode: $([[ "$apply_mode" -eq 1 ]] && printf 'apply' || printf 'dry run')"
printf '\n'

ssh_ok_out="$(mktemp)"
ssh_ok_err="$(mktemp)"
if "${ssh_cmd[@]}" 'printf "__codex_remote_ok__\n"' >"$ssh_ok_out" 2>"$ssh_ok_err"; then
  if grep -q '__codex_remote_ok__' "$ssh_ok_out"; then
    pass "SSH login succeeded."
  else
    sed 's/^/      /' "$ssh_ok_err" >&2 || true
    die "SSH returned, but the expected marker was missing"
  fi
else
  sed 's/^/      /' "$ssh_ok_err" >&2 || true
  die "SSH login failed"
fi
rm -f "$ssh_ok_out" "$ssh_ok_err"

codex_out="$(mktemp)"
codex_err="$(mktemp)"
if "${ssh_cmd[@]}" 'command -v codex && codex app-server --help >/dev/null 2>&1' >"$codex_out" 2>"$codex_err"; then
  pass "Plain SSH sees codex at: $(sed -n '1p' "$codex_out" | tr -d '\r')"
else
  if "${ssh_cmd[@]}" 'command -v codex' >"$codex_out" 2>"$codex_err"; then
    sed 's/^/      /' "$codex_err" >&2 || true
    die "plain SSH found codex at $(sed -n '1p' "$codex_out" | tr -d '\r'), but \`codex app-server\` failed. SSH in normally, run \`command -v codex\`, then add that directory near the top of ~/.bashrc and try again."
  fi

  sed 's/^/      /' "$codex_err" >&2 || true
  die "plain SSH could not find \`codex\`. SSH in normally, run \`command -v codex\`, then add that directory near the top of ~/.bashrc and try again."
fi
rm -f "$codex_out" "$codex_err"

if [[ "$apply_mode" -eq 0 ]]; then
  printf '\n'
  info "Dry run complete."
  info "Re-run with --apply to write $config_path."
  exit 0
fi

write_config "$config_path"

printf '\n'
info "Next:"
info "1. Restart Codex."
info "2. Open Codex > Hosts > (remote) ..."
info "3. In the remote window, choose File > Open Folder..."
info "4. Enter ~/ or your project path."
